name: Transformations challenge entry template
description: please submit transfrmtation details here
title: "[Transformation Challenge]: "
labels: ["challenge"]
assignees:
  - gitcommitshow, saramashfej
body:
  - type: markdown
    attributes:
      value: |
        Thank you for entering the Transformations challenge!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown 
    id: Language
    attributes:
      label: Language
      description: What was the programming language you were using?
      options:
        - Javascript
        - Python
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: category
      description: What category of Transformations does this fall under?
      multiple: true
      options:
        - Data Security and Governance
        - Data Processing and Enrichment
        - Data Cleaning and Routing 
        - Custom/others 
     validations:
     required: true
  - type: textarea
    id: description
    attributes:
      label: description
      description: Please provide a short description about this Transformation
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
